version: '3.8'

services:
  # Base de Datos para Ventas
  db-ventas:
    image: mysql:8.0
    container_name: db-ventas
    restart: always
    environment:
      MYSQL_DATABASE: db_ventas
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - v_ventas_data:/var/lib/mysql # Persistencia de datos requerida por la rúbrica
    networks:
      - innova-network

  # Base de Datos para Despachos
  db-despachos:
    image: mysql:8.0
    container_name: db-despachos
    restart: always
    environment:
      MYSQL_DATABASE: db_despacho
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - v_despacho_data:/var/lib/mysql # Persistencia de datos requerida por la rúbrica
    networks:
      - innova-network

  # Microservicio Ventas (Spring Boot)
  back-ventas:
    image: ${ECR_REGISTRY}/microservicio_de_ventas:latest
    container_name: back-ventas
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db-ventas
    environment:
      - DB_ENDPOINT=db-ventas
      - DB_PORT=3306
      - DB_NAME=db_ventas
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - innova-network

  # Microservicio Despachos (Spring Boot)
  back-despachos:
    image: ${ECR_REGISTRY}/microservicio_de_despacho:latest
    container_name: back-despachos
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db-despachos
    environment:
      - DB_ENDPOINT=db-despachos
      - DB_PORT=3306
      - DB_NAME=db_despacho
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - innova-network

networks:
  innova-network:
    driver: bridge # Red aislada para cumplir seguridad del examen

volumes:
  v_ventas_data:
  v_despacho_data: