name: Deploy Backend Ventas

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: microservicio_de_ventas # Nombre exacto que me diste
        run: |
          # Construye usando la subcarpeta correcta del microservicio
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./back-Ventas_SpringBoot/Springboot-API-REST-VENTA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # IP de tu instancia de Backend
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # La llave que pegarás en los secretos
          script: |
            # Login en ECR dentro de la instancia
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            
            # Limpiar y ejecutar el nuevo contenedor
            docker pull ${{ secrets.ECR_REGISTRY }}/microservicio_de_ventas:latest
            docker stop back-ventas || true
            docker rm back-ventas || true
            docker run -d --name back-ventas -p 8081:8080 ${{ secrets.ECR_REGISTRY }}/microservicio_de_ventas:latest