name: Deploy Backend Ventas

on:
  push:
    branches: [ "deploy" ] # Se activa solo en la rama deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest ./back-Ventas_SpringBoot
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest
            docker stop back-ventas || true
            docker rm back-ventas || true
            docker run -d --name back-ventas -p 8081:8080 ${{ secrets.DOCKERHUB_USERNAME }}/back-ventas:latest
